name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: eventuser
          POSTGRES_PASSWORD: eventpass
          POSTGRES_DB: eventdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Test Auth Service
      run: |
        cd auth-service
        go test -v ./...

    - name: Test Event Service
      run: |
        cd event-service
        go test -v ./...

    - name: Test User Interaction Service
      run: |
        cd user-interaction-service
        go test -v ./...

    - name: Test Notification Service
      run: |
        cd notification-service
        go test -v ./...

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Auth Service
      uses: docker/build-push-action@v4
      with:
        context: ./auth-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:latest

    - name: Build and push Event Service
      uses: docker/build-push-action@v4
      with:
        context: ./event-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/event-service:latest

    - name: Build and push User Interaction Service
      uses: docker/build-push-action@v4
      with:
        context: ./user-interaction-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-interaction-service:latest

    - name: Build and push Notification Service
      uses: docker/build-push-action@v4
      with:
        context: ./notification-service
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/notification-service:latest 